# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Abdk4Moura.Tunlion
PackageVersion: "0.2.1-beta.19"
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: tunlion.exe
    PortableCommandAlias: tunlion
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Abdk4Moura/tunlion/releases/download/cli-v0.2.1-beta.19/filament-x86_64-pc-windows-msvc.zip
    InstallerSha256: "388273368723a19f2826579f4e5aff9578a76a194a213654bc3d713bad90d3b4"
Dependencies:
  PackageDependencies:
ReleaseDate: "2026-06-25"
ManifestType: installer
ManifestVersion: 1.6.0
