# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Abdk4Moura.Tunlion
PackageVersion: "0.2.1-beta.18"
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: tunlion.exe
    PortableCommandAlias: tunlion
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Abdk4Moura/tunlion/releases/download/cli-v0.2.1-beta.18/filament-x86_64-pc-windows-msvc.zip
    InstallerSha256: "900a50e9ad0c11de775f987953eeb10f2605abe896c34435f7482bf288c0b53a"
Dependencies:
  PackageDependencies:
ReleaseDate: "2026-06-25"
ManifestType: installer
ManifestVersion: 1.6.0
